### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by abhisheksett** [Badestrand/node-mysql-deadlock-retries#2]
I'm getting following error intermittently:

TypeError: callback is not a function
    at Query.handleResponse (/app/node_modules/node-mysql-deadlock-retries/index.js:47:11)
    at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/app/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)

This is causing my node server to crash. How to resolve this?

**Comment by veryinterestingio** [comment]
This is difficult to answer for me without seeing more code. It seems like you passed something that is not a callback as the third parameter to `query`.

**Comment by Badestrand** [comment]
This is difficult to answer for me without seeing more code. It seems like you passed something that is not a callback as the third parameter to query.
